# CI build placeholder
name: Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests (placeholder)
        run: echo "Run tests"
